GET http://localhost:5000/api/patients

###
POST http://localhost:5000/api/patients
Content-Type: application/json

{
  "name": "Rahul Sharma",
  "age": 45,
  "gender": "Male"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "employeeId": "ADM001",
  "name": "Hospital Admin",
  "password": "admin123",
  "role": "ADMIN"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "employeeId": "ADM001",
  "password": "admin123"
}

###
GET http://localhost:5000/api/patients
Authorization: Bearer YOUR_TOKEN_HERE

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "employeeId": "ADM001",
  "password": "admin123"
}

###
GET http://localhost:5000/api/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYzA4NDBlMi1hYTJhLTQxYzMtODI0ZC0yZGJkODNiNWE3MTAiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NzMyNTQ0NzQsImV4cCI6MTc3MzI4MzI3NH0.AADUd90fltWveCt-l3Ij3_otXfQOk03H4shzM7tm9O0
